In [1]:
import selenium
from selenium import webdriver
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.keys import Keys
import time
from bs4 import BeautifulSoup

In [2]:
cd="/Users/tzuchyi/Downloads/chromedriver"

In [26]:
browser = webdriver.Chrome(cd)
browser.get("https://www.agoda.com/zh-tw/fushin-hotel-taipei/hotel/taipei-tw.html?checkin=2020-01-07&los=1&adults=1&rooms=1&cid=1826371&tag=c9eb0777-faac-f238-8d4b-05488b8a3d0f&searchrequestid=d1931e0a-9717-4d56-8f40-0b1833f7f9b9&travellerType=-1&tspTypes=1&cabinType=Economy&tabbed=true")
#browser.driver.set_window_size(1440, 816)


browser.execute_script("window.scrollTo(0, document.body.scrollHeight)")

time.sleep(1)

#for ele in soup.select(".Review-comment-body p.Review-comment-bodyText"):
#    print(ele.text)
#browser.find_element_by_xpath('//*[contains(concat( " ", @class, " " ), concat( " ", "ficon-carrouselarrow-right", " " ))]').click()
for i in range(27):
    for ele in soup.select(".Review-comment-body p.Review-comment-bodyText"):
        print(ele.text)
    browser.find_element_by_xpath('//*[contains(concat( " ", @class, " " ), concat( " ", "ficon-carrouselarrow-right", " " ))]').click()
    soup = BeautifulSoup(browser.page_source)
browser.close()

    #browser.find_element("paginationNext").click()
    #soup = BeautifulSoup(browser.page_source)
#browser.close()

ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=79.0.3945.88)


In [29]:
browser = webdriver.Chrome(cd)
browser.get("https://www.agoda.com/zh-tw/fushin-hotel-taipei/hotel/taipei-tw.html?checkin=2020-01-07&los=1&adults=1&rooms=1&cid=1826371&tag=c9eb0777-faac-f238-8d4b-05488b8a3d0f&searchrequestid=d1931e0a-9717-4d56-8f40-0b1833f7f9b9&travellerType=-1&tspTypes=1&cabinType=Economy&tabbed=true")
#browser.driver.set_window_size(1440, 816)


browser.execute_script("window.scrollTo(0, document.body.scrollHeight)")

time.sleep(1)
#soup = BeautifulSoup(browser.page_source)
for ele in soup.select(".Review-comment-body p.Review-comment-bodyText"):
    print(ele.text)
browser.find_element_by_xpath('//*[contains(concat( " ", @class, " " ), concat( " ", "ficon-carrouselarrow-right", " " ))]').click()
browser.execute_script("window.scrollTo(0, document.body.scrollHeight)")
time.sleep(1)
soup = BeautifulSoup(browser.page_source)
for ele in soup.select(".Review-comment-body p.Review-comment-bodyText"):
    print(ele.text)

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[contains(concat( " ", @class, " " ), concat( " ", "ficon-carrouselarrow-right", " " ))]"}
  (Session info: chrome=79.0.3945.88)


In [38]:
browser = webdriver.Chrome(cd)
browser.get("https://www.agoda.com/zh-tw/fushin-hotel-taipei/hotel/taipei-tw.html?checkin=2020-01-07&los=1&adults=1&rooms=1&cid=1826371&tag=c9eb0777-faac-f238-8d4b-05488b8a3d0f&searchrequestid=d1931e0a-9717-4d56-8f40-0b1833f7f9b9&travellerType=-1&tspTypes=1&cabinType=Economy&tabbed=true")
browser.set_window_size(1440, 816)
browser.execute_script("window.scrollTo(0,143)")
browser.execute_script("window.scrollTo(0,821)")
browser.execute_script("window.scrollTo(0,6980)")
browser.execute_script("window.scrollTo(0,8160)")
browser.execute_script("window.scrollTo(0,16415)")
browser.execute_script("window.scrollTo(0,20161)")
browser.execute_script("window.scrollTo(0, document.body.scrollHeight)")

time.sleep(1)
soup = BeautifulSoup(browser.page_source)
for ele in soup.select(".Review-comment-body p.Review-comment-bodyText"):
    print(ele.text)


因為剛開幕時入住感受極佳  這次已再相隔四年入住所以這次再選擇富信 一切本來都還不錯 雖然跟剛開幕比是有一丁點落差 但整體還是不錯 but.......
睡到半夜三點被冷氣機漏水聲音滴到地毯聲音吵醒
開燈一看 出風口旁已被滲水裂出一條痕跡  打電話給服務中心派人來看之後就跑到走廊打電話請師傅來 
整個過程拖了20-30分才問我們要不要換房 我問說那可以先離開讓我們換個衣服嗎?師傅也不為所動
我們只好到廁所去換，然後把睡夢中的小孩抱到新房間(這時已經4點左右) 之後飯店也沒主動提出要給任何補償 我才打給飯店問能不能延後退房 櫃台回我只能延一小時 但睡眠被中斷之後翻來覆去好久才再入睡 隔天起來超疲憊 退房時也沒人因為此事向我們打聲招呼 實在遺憾
1. 住宿很多次了,  浴室的設施一直都有狀況, 譬如淋浴間的門無法密合關門, 這次住宿蓮蓬頭都已經壞掉了
2. 浴巾沒有清洗乾淨, 咖啡杯沒有洗乾淨
3. agoda有提供"提前入住的需求"的選項, 但是飯店都沒有回覆可不可以, 等到要入住了, 打電話去問"也僅回覆不敢保證", 等到我到飯店, 飯店真的讓客人在大廳等1個小時, 更令人生氣的是, 同樣是無法提早入住, 櫃台人員親自把房間門卡送到同樣在大廳等待的外國客人, 而我卻是在大廳等1個小時, 然後還要自己去跟櫃台人員拿門卡, 原來飯店的櫃台人員是歧視本國籍的旅客
優點：
飯店整潔度佳，且非常貼心於床頭及Mini Bar均擺設礦泉水，備品齊全，牙刷是小刷頭的十分加分，房務無可挑剔。
健身房設備齊全，空間適中不壅擠，三溫暖非常乾淨，晚上或早晨適合泡一泡放鬆。
早餐樣式種類不少，該有的都有且調味不差。
價格相當實惠，服務態度適中，不過度殷勤。
飯店整體適合商務旅行，或員工訓練、會議用途。

缺點：
雖然是觀光局五星級飯店，但是整體較無特色（無景觀、特殊設施或活動安排，非度假或豪華酒店取向），較適合商務或是團體會議使用。
另外三溫暖應提醒住客是裸湯，免得有人有裸體有人穿泳衣褲，使用起來十分尷尬。
以五星級飯店來說 這樣的房價算很優惠的了~ 如果以我所住過的五星級飯店來說 這裡有很多可以進步的空間! 例如早餐很多都是冷的 不知是我大約9:15左右吃的關係嗎? 不過他的台南擔仔麵溫暖的我的胃跟心! 而他早餐餐廳的裝潢擄獲我老婆的拍照慾望，飯店有小孩遊戲室，三溫暖(雖然是泡自來水)，如

In [296]:
browser = webdriver.Chrome(cd)
browser.get("https://www.agoda.com/zh-tw/search?asq=Uq62oMmDO92bLOxpntQ%2BTEvZuBN2f6E8NhdcdV4DkxOdfPxko8DuO%2Fy%2FTMh7ahoqBocoyS7DIWqeheAl2KchTch924cAsjjhJhdSTXeUCklkivsbECS3yPcj2WgKNbRfV2wSZTw3HszKHRMToXsIr0NZuqqmX9jF%2FPBQ2%2ByXuvw%3D&city=4951&cid=1826371&tag=ab92ca0a-b803-8f27-c188-fe307db02490&tick=637133029320&languageId=20&userId=197c05ba-990e-4b8a-9036-ac7222c312f9&sessionId=mhwg1154zvqwruu1n54i0j0c&pageTypeId=7&origin=TW&locale=zh-TW&aid=82361&currencyCode=TWD&htmlLanguage=zh-tw&cultureInfoName=zh-TW&ckuid=197c05ba-990e-4b8a-9036-ac7222c312f9&prid=0&checkIn=2020-01-07&checkOut=2020-01-08&rooms=1&adults=1&children=0&priceCur=TWD&los=1&textToSearch=%E5%8F%B0%E5%8C%97%E5%B8%82&travellerType=0&familyMode=off&ro=C00000&productType=-1&hotelStarRating=4&sort=agodaRecommended")

for i in range(10):
    browser.execute_script("window.scrollTo(0, document.body.scrollHeight)")
    time.sleep(1)
soup = BeautifulSoup(browser.page_source)
for ele,ele2 in zip(soup.select(".InfoBox__Header h3"),soup.select(".PropertyCardItem.ssr-search-result a")):
    print(ele.text)
    print(ele.text[-4:])
    print(ele2.get("href"))



蘊泉庄 (Yun Estate Hotel)
tel)
/zh-tw/yun-estate-hotel/hotel/taipei-tw.html?checkin=2020-01-07&los=1&adults=1&rooms=1&ro=C00000&cid=1826371&tag=ab92ca0a-b803-8f27-c188-fe307db02490&searchrequestid=165ddd1c-d8a1-4857-9e21-3fc5ac935648&travellerType=0&tspTypes=16&cabinType=Economy
宜家商旅 (La Maison Hotel)
tel)
/zh-tw/la-maison-hotel/hotel/taipei-tw.html?checkin=2020-01-07&los=1&adults=1&rooms=1&ro=C00000&cid=1826371&tag=ab92ca0a-b803-8f27-c188-fe307db02490&searchrequestid=165ddd1c-d8a1-4857-9e21-3fc5ac935648&travellerType=0&cabinType=Economy
台北馥華商旅 - 敦北館 (Simple+ Hotel)
tel)
/zh-tw/hotel-cham-cham-taipei_2/hotel/taipei-tw.html?checkin=2020-01-07&los=1&adults=1&rooms=1&ro=C00000&cid=1826371&tag=ab92ca0a-b803-8f27-c188-fe307db02490&searchrequestid=165ddd1c-d8a1-4857-9e21-3fc5ac935648&travellerType=0&tspTypes=8,1,16&cabinType=Economy
倆人旅店 (Hotel Double One)
One)
/zh-tw/taipei-fullerton-hotel-east/hotel/taipei-tw.html?checkin=2020-01-07&los=1&adults=1&rooms=1&ro=C00000&cid=1826371&tag=ab92ca0a-b8

In [ ]:
for ele in soup.select(".InfoBox__Header h3"):
    print(ele.text)
for ele in soup.select(".PropertyCardItem.ssr-search-result a"):
    print(ele.get("href"))
browser.close()

In [64]:
Fushin=[] 

In [65]:
browser = webdriver.Chrome(cd)
browser.get("https://www.agoda.com/zh-tw/fushin-hotel-taipei/hotel/taipei-tw.html?checkin=2020-01-07&los=1&adults=1&rooms=1&cid=1826371&tag=c9eb0777-faac-f238-8d4b-05488b8a3d0f&searchrequestid=d1931e0a-9717-4d56-8f40-0b1833f7f9b9&travellerType=-1&tspTypes=1&cabinType=Economy&tabbed=true")
browser.set_window_size(1440, 816)
for i in range(5):
    browser.execute_script("window.scrollTo(0, document.body.scrollHeight)")
    time.sleep(1)
soup = BeautifulSoup(browser.page_source)
for ele in soup.select(".Review-comment-body p.Review-comment-bodyText"):
    Fushin.append(ele.text)
browser.close()

In [66]:
len(Fushin)

20

In [81]:
Fushin=[] 
browser = webdriver.Chrome(cd)
browser.get("https://www.agoda.com/zh-tw/fushin-hotel-taipei/hotel/taipei-tw.html?checkin=2020-01-07&los=1&adults=1&rooms=1&cid=1826371&tag=c9eb0777-faac-f238-8d4b-05488b8a3d0f&searchrequestid=d1931e0a-9717-4d56-8f40-0b1833f7f9b9&travellerType=-1&tspTypes=1&cabinType=Economy&tabbed=true")
browser.set_window_size(1440, 816)
for i in range(3):
    browser.execute_script("window.scrollTo(0,143)")
    browser.execute_script("window.scrollTo(0,821)")
    browser.execute_script("window.scrollTo(0,6980)")
    browser.execute_script("window.scrollTo(0,8160)")
    browser.execute_script("window.scrollTo(0,16415)")
    browser.execute_script("window.scrollTo(0,20161)")
    browser.execute_script("window.scrollTo(0, document.body.scrollHeight)")

    time.sleep(1)
    soup = BeautifulSoup(browser.page_source)
    for ele in soup.select(".Review-comment-body p.Review-comment-bodyText"):
        #Fushin.append(ele.text)
        print(ele.text)
    browser.find_element_by_css_selector(".Review-paginator:nth-child(6) .ficon-carrouselarrow-right").click()

browser.close()

因為剛開幕時入住感受極佳  這次已再相隔四年入住所以這次再選擇富信 一切本來都還不錯 雖然跟剛開幕比是有一丁點落差 但整體還是不錯 but.......
睡到半夜三點被冷氣機漏水聲音滴到地毯聲音吵醒
開燈一看 出風口旁已被滲水裂出一條痕跡  打電話給服務中心派人來看之後就跑到走廊打電話請師傅來 
整個過程拖了20-30分才問我們要不要換房 我問說那可以先離開讓我們換個衣服嗎?師傅也不為所動
我們只好到廁所去換，然後把睡夢中的小孩抱到新房間(這時已經4點左右) 之後飯店也沒主動提出要給任何補償 我才打給飯店問能不能延後退房 櫃台回我只能延一小時 但睡眠被中斷之後翻來覆去好久才再入睡 隔天起來超疲憊 退房時也沒人因為此事向我們打聲招呼 實在遺憾
1. 住宿很多次了,  浴室的設施一直都有狀況, 譬如淋浴間的門無法密合關門, 這次住宿蓮蓬頭都已經壞掉了
2. 浴巾沒有清洗乾淨, 咖啡杯沒有洗乾淨
3. agoda有提供"提前入住的需求"的選項, 但是飯店都沒有回覆可不可以, 等到要入住了, 打電話去問"也僅回覆不敢保證", 等到我到飯店, 飯店真的讓客人在大廳等1個小時, 更令人生氣的是, 同樣是無法提早入住, 櫃台人員親自把房間門卡送到同樣在大廳等待的外國客人, 而我卻是在大廳等1個小時, 然後還要自己去跟櫃台人員拿門卡, 原來飯店的櫃台人員是歧視本國籍的旅客
優點：
飯店整潔度佳，且非常貼心於床頭及Mini Bar均擺設礦泉水，備品齊全，牙刷是小刷頭的十分加分，房務無可挑剔。
健身房設備齊全，空間適中不壅擠，三溫暖非常乾淨，晚上或早晨適合泡一泡放鬆。
早餐樣式種類不少，該有的都有且調味不差。
價格相當實惠，服務態度適中，不過度殷勤。
飯店整體適合商務旅行，或員工訓練、會議用途。

缺點：
雖然是觀光局五星級飯店，但是整體較無特色（無景觀、特殊設施或活動安排，非度假或豪華酒店取向），較適合商務或是團體會議使用。
另外三溫暖應提醒住客是裸湯，免得有人有裸體有人穿泳衣褲，使用起來十分尷尬。
以五星級飯店來說 這樣的房價算很優惠的了~ 如果以我所住過的五星級飯店來說 這裡有很多可以進步的空間! 例如早餐很多都是冷的 不知是我大約9:15左右吃的關係嗎? 不過他的台南擔仔麵溫暖的我的胃跟心! 而他早餐餐廳的裝潢擄獲我老婆的拍照慾望，飯店有小孩遊戲室，三溫暖(雖然是泡自來水)，如

ElementClickInterceptedException: Message: element click intercepted: Element <i class="ficon ficon-24 ficon-carrouselarrow-right"></i> is not clickable at point (850, 12). Other element would receive the click: <div data-selenium="checkOutBox" data-date="2020-01-08" class="SearchBoxTextDescription SearchBoxTextDescription--checkOut">...</div>
  (Session info: chrome=79.0.3945.88)


In [106]:
len(Fushin)

40

'這趟旅行是家族之旅，有3歲的小孩同行，房務安排了壁貼與玩具都齊全的孩童房，這點蠻驚喜的，小朋友很喜歡。不過切記一定要訂富有早餐的房型，不然附近都沒有早餐店實在很麻煩。有接駁車，不過回程在南港展覽館六號出口卻沒有顯示停等位置，還要打電話向房務確認，這個有些小麻煩。房間設施還不錯，空間確實很大，備品也齊全，可惜沒有HDMI線。第一日入房房間空調有潮濕霉味，向櫃檯反映後送上了一台空氣清淨機。'

In [3]:
browser = webdriver.Chrome(cd)
browser.get("https://www.agoda.com/zh-tw/fushin-hotel-taipei/hotel/taipei-tw.html?checkin=2020-01-07&los=1&adults=1&rooms=1&cid=1826371&tag=c9eb0777-faac-f238-8d4b-05488b8a3d0f&searchrequestid=d1931e0a-9717-4d56-8f40-0b1833f7f9b9&travellerType=-1&tspTypes=1&cabinType=Economy&tabbed=true")
Fushin=[] 
for j in range(2):

    for i in range(5):
        browser.execute_script("window.scrollTo(0, document.body.scrollHeight)")
        time.sleep(1)
    soup = BeautifulSoup(browser.page_source,'html.parser')
    for ele in soup.select(".Review-comment-body p.Review-comment-bodyText"):
        print(ele.text)
        Fushin.append([ele.text])
    browser.find_element_by_css_selector(".Review-paginator:nth-child(6) .ficon-carrouselarrow-right").click()
    for i in range(5):
        browser.execute_script("window.scrollTo(0, document.body.scrollHeight)")
        time.sleep(1)
    soup = BeautifulSoup(browser.page_source,'html.parser')
    for ele in soup.select(".Review-comment-body p.Review-comment-bodyText"):
        print(ele.text)
        Fushin.append(ele.text)
    browser.find_element_by_css_selector(".Review-paginator:nth-child(4) .ficon-carrouselarrow-right").click()
browser.close()

因為剛開幕時入住感受極佳  這次已再相隔四年入住所以這次再選擇富信 一切本來都還不錯 雖然跟剛開幕比是有一丁點落差 但整體還是不錯 but.......
睡到半夜三點被冷氣機漏水聲音滴到地毯聲音吵醒
開燈一看 出風口旁已被滲水裂出一條痕跡  打電話給服務中心派人來看之後就跑到走廊打電話請師傅來 
整個過程拖了20-30分才問我們要不要換房 我問說那可以先離開讓我們換個衣服嗎?師傅也不為所動
我們只好到廁所去換，然後把睡夢中的小孩抱到新房間(這時已經4點左右) 之後飯店也沒主動提出要給任何補償 我才打給飯店問能不能延後退房 櫃台回我只能延一小時 但睡眠被中斷之後翻來覆去好久才再入睡 隔天起來超疲憊 退房時也沒人因為此事向我們打聲招呼 實在遺憾
1. 住宿很多次了,  浴室的設施一直都有狀況, 譬如淋浴間的門無法密合關門, 這次住宿蓮蓬頭都已經壞掉了
2. 浴巾沒有清洗乾淨, 咖啡杯沒有洗乾淨
3. agoda有提供"提前入住的需求"的選項, 但是飯店都沒有回覆可不可以, 等到要入住了, 打電話去問"也僅回覆不敢保證", 等到我到飯店, 飯店真的讓客人在大廳等1個小時, 更令人生氣的是, 同樣是無法提早入住, 櫃台人員親自把房間門卡送到同樣在大廳等待的外國客人, 而我卻是在大廳等1個小時, 然後還要自己去跟櫃台人員拿門卡, 原來飯店的櫃台人員是歧視本國籍的旅客
優點：
飯店整潔度佳，且非常貼心於床頭及Mini Bar均擺設礦泉水，備品齊全，牙刷是小刷頭的十分加分，房務無可挑剔。
健身房設備齊全，空間適中不壅擠，三溫暖非常乾淨，晚上或早晨適合泡一泡放鬆。
早餐樣式種類不少，該有的都有且調味不差。
價格相當實惠，服務態度適中，不過度殷勤。
飯店整體適合商務旅行，或員工訓練、會議用途。

缺點：
雖然是觀光局五星級飯店，但是整體較無特色（無景觀、特殊設施或活動安排，非度假或豪華酒店取向），較適合商務或是團體會議使用。
另外三溫暖應提醒住客是裸湯，免得有人有裸體有人穿泳衣褲，使用起來十分尷尬。
以五星級飯店來說 這樣的房價算很優惠的了~ 如果以我所住過的五星級飯店來說 這裡有很多可以進步的空間! 例如早餐很多都是冷的 不知是我大約9:15左右吃的關係嗎? 不過他的台南擔仔麵溫暖的我的胃跟心! 而他早餐餐廳的裝潢擄獲我老婆的拍照慾望，飯店有小孩遊戲室，三溫暖(雖然是泡自來水)，如

ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=79.0.3945.88)


In [104]:
Fushin_p2=Fushin

In [4]:
Fushin

[['因為剛開幕時入住感受極佳  這次已再相隔四年入住所以這次再選擇富信 一切本來都還不錯 雖然跟剛開幕比是有一丁點落差 但整體還是不錯 but.......\n睡到半夜三點被冷氣機漏水聲音滴到地毯聲音吵醒\n開燈一看 出風口旁已被滲水裂出一條痕跡  打電話給服務中心派人來看之後就跑到走廊打電話請師傅來 \n整個過程拖了20-30分才問我們要不要換房 我問說那可以先離開讓我們換個衣服嗎?師傅也不為所動\n我們只好到廁所去換，然後把睡夢中的小孩抱到新房間(這時已經4點左右) 之後飯店也沒主動提出要給任何補償 我才打給飯店問能不能延後退房 櫃台回我只能延一小時 但睡眠被中斷之後翻來覆去好久才再入睡 隔天起來超疲憊 退房時也沒人因為此事向我們打聲招呼 實在遺憾'],
 ['1. 住宿很多次了,  浴室的設施一直都有狀況, 譬如淋浴間的門無法密合關門, 這次住宿蓮蓬頭都已經壞掉了\n2. 浴巾沒有清洗乾淨, 咖啡杯沒有洗乾淨\n3. agoda有提供"提前入住的需求"的選項, 但是飯店都沒有回覆可不可以, 等到要入住了, 打電話去問"也僅回覆不敢保證", 等到我到飯店, 飯店真的讓客人在大廳等1個小時, 更令人生氣的是, 同樣是無法提早入住, 櫃台人員親自把房間門卡送到同樣在大廳等待的外國客人, 而我卻是在大廳等1個小時, 然後還要自己去跟櫃台人員拿門卡, 原來飯店的櫃台人員是歧視本國籍的旅客'],
 ['優點：\n飯店整潔度佳，且非常貼心於床頭及Mini Bar均擺設礦泉水，備品齊全，牙刷是小刷頭的十分加分，房務無可挑剔。\n健身房設備齊全，空間適中不壅擠，三溫暖非常乾淨，晚上或早晨適合泡一泡放鬆。\n早餐樣式種類不少，該有的都有且調味不差。\n價格相當實惠，服務態度適中，不過度殷勤。\n飯店整體適合商務旅行，或員工訓練、會議用途。\n\n缺點：\n雖然是觀光局五星級飯店，但是整體較無特色（無景觀、特殊設施或活動安排，非度假或豪華酒店取向），較適合商務或是團體會議使用。\n另外三溫暖應提醒住客是裸湯，免得有人有裸體有人穿泳衣褲，使用起來十分尷尬。'],
 ['以五星級飯店來說 這樣的房價算很優惠的了~ 如果以我所住過的五星級飯店來說 這裡有很多可以進步的空間! 例如早餐很多都是冷的 不知是我大約9:15左右吃的關係嗎? 不過他的台南擔仔麵溫暖的我的胃跟心! 而他早餐餐廳的

In [5]:
import os
from pathlib import Path
from ckiptagger import WS,POS,NER
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
import urllib.request
import zipfile
import pandas as pd
from sklearn.metrics.classification import accuracy_score, confusion_matrix
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or 

In [277]:
new_data=Fushin
path=os.path.join(str(Path.home()),"ckip/")
ckip_ws=WS(os.path.join(path,"data"))
ckip_pos=POS(os.path.join(path,"data"))
ckip_ner=NER(os.path.join(path,"data"))

dataset=[]
for q in range(len(new_data)):
    k=new_data[q]
    chinese_sentence=k  
    zh_doc_ws=ckip_ws(chinese_sentence)      
    zh_doc_pos=ckip_pos(zh_doc_ws)    
    zh_doc_ner=ckip_ner(zh_doc_ws,zh_doc_pos)
    word_only=[]
    for i,sentence in enumerate(zh_doc_ner):
        for j,(start_idx,end_index,ner_type,word) in enumerate(sentence):
            word_only.append("{}".format(word))
    dataset.append(word_only)
    

In [129]:
dataset

[['半夜三點', '4點', '四年', '20-30分', '一小時', '隔天'],
 ['1個小時', '1個小時', '1'],
 ['早晨', '三溫暖', '晚上', '三溫暖', '觀光局'],
 ['五星級', '台北信義區', 'COSTCO', '南港展覽館', '台南', '三溫暖'],
 ['一年', '國道一', '三汐止交流道', '第二'],
 ['張空席', '一半'],
 [],
 [],
 [],
 ['6點', '南港展覽館', '5點半', '6點', '捷運', '10-20'],
 [],
 ['半夜'],
 [],
 [],
 [],
 ['一大早'],
 ['12點', '早上'],
 ['南港展覽館捷運站',
  '24',
  '前一晚',
  '加賀屋',
  '溫泉飯店',
  '當天',
  '兩',
  '初四',
  '1米',
  '一',
  '早上',
  '晚上',
  '一',
  '當晚',
  '四',
  '台灣',
  '溫泉飯店',
  '兩',
  '150'],
 ['兩', '10數'],
 ['3歲', '南港展覽館', '第一']]

In [275]:
import jieba
import jieba.posseg as pseg
URL="http://github.com/fxsjy/jieba/raw/master/extra_dict/dict.txt.big"
if not os.path.exists(os.path.join(os.getcwd(),"dict.txt.big")):
    urllib.request.urlretrieve(URL,"dict.txt.big")
jieba.set_dictionary("dict.txt.big")

In [ ]:
for i,(word,pos) in enumerate(zh_doc):
    print("{}".format(word))

In [ ]:
dataset=[]
new_data=Fushin
for q in range(len(new_data)):
    k=new_data[q]
    chinese_sentence=k[0]  
    seg_full=jieba.cut(chinese_sentence,cut_all=True)
    seg_accurate=jieba.cut(chinese_sentence,cut_all=False)
    seg_search=jieba.cut_for_search(chinese_sentence)
    zh_doc=pseg.cut(chinese_sentence)
    word_only=[]
    for i,(word,pos) in enumerate(zh_doc):
        word_only.append("{}".format(word))
    dataset.append(word_only)

In [291]:
dataset=[]
new_data=Fushin
for q in range(len(new_data)):
    k=new_data[q]
    chinese_sentence=k[0]  
    seg_full=jieba.cut(chinese_sentence,cut_all=True)
    seg_accurate=jieba.cut(chinese_sentence,cut_all=False)
    seg_search=jieba.cut_for_search(chinese_sentence)
    zh_doc=pseg.cut(chinese_sentence)
    word_only=[]
    for i,(word,pos) in enumerate(zh_doc):
        if "{}".format(pos)=="n":
            word_only.append("{}".format(word))
    dataset.append(word_only)

In [292]:
dataset[0]

['漏水', '地毯', '人', '走廊', '衣服', '小孩', '問能', '房', '櫃台']

In [294]:
#關聯規則
te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_)
frequent_itemsets = apriori(df, min_support=0.2, use_colnames=True)
print(frequent_itemsets)





   support itemsets
0      0.2      (人)
1      0.2     (住宿)
2      0.2      (房)
3      0.5     (早餐)
4      0.2     (櫃台)


In [12]:
print('item: {}'.format(te.columns_))

item: ['\n', '\r\n', ' ', '!', '"', '(', ')', ',', '-', '.', '..', '...', '.......', '/', '1', '1.', '10', '12', '15', '150', '2.', '20', '24', '3', '3.', '30', '4', '4.', '5', '5.', '6', '6.', '7.', '9', '9.', ':', '?', 'Bar', 'CM', 'COSTCO', 'CP', 'HDMI', 'Mini', 'P', 'S', 'agoda', 'but', 'hr', 'ok', '~', '“', '、', '。', '一', '一丁點', '一再', '一切', '一半', '一只', '一台', '一大早', '一套', '一定', '一年', '一條', '一樣', '一直', '一邊', '一間', '三', '三溫暖', '三點', '上', '下次', '不', '不便', '不到', '不多', '不太好', '不好', '不少', '不怕', '不敢', '不是', '不會', '不然', '不理', '不用說', '不知', '不能', '不要', '不過', '不錯', '且', '中', '中斷', '主動', '之', '之前', '之後', '之間', '也', '乾淨', '了', '五星級', '些', '交流', '交通工具', '享受', '人', '人員', '人房', '什麼', '仔', '他', '令人', '以', '以前', '以外', '以後', '任何', '但', '但一', '但是', '佈置', '位置', '住', '住客', '住宿', '你', '佳', '佷', '使用', '來', '來不及', '來看', '來說', '例如', '便宜', '保證', '保養', '信用卡', '信義', '個', '值得', '值高', '假設', '偏僻', '做', '停', '停車位', '停車場', '健身房', '備品', '僅', '價格', '優', '優惠', '優格', '優點', '先', '免得', '免費', '入', '入住', '入席', '入睡', '內', '

In [24]:
newdata=[]
for i in range(len(new_data)):
    newdata.append(new_data[i])

In [25]:
import zipfile
import pandas as pd

In [26]:
dataframe= pd.DataFrame(newdata,columns=["sentence"])

In [27]:
dataframe= pd.DataFrame(comment,columns=["comment"])
dataframe["score"]=score
dataframe.to_csv('v2.csv')

sentence
0   因為剛開幕時入住感受極佳  這次已再相隔四年入住所以這次再選擇富信 一切本來都還不錯 雖然跟...
1   1. 住宿很多次了,  浴室的設施一直都有狀況, 譬如淋浴間的門無法密合關門, 這次住宿蓮蓬...
2   優點：\n飯店整潔度佳，且非常貼心於床頭及Mini Bar均擺設礦泉水，備品齊全，牙刷是小刷...
3   以五星級飯店來說 這樣的房價算很優惠的了~ 如果以我所住過的五星級飯店來說 這裡有很多可以進...
4   近國道一、國道三汐止交流道，飯店地下室附停車場，開車很方便!\n\n館內設施不多，但大體上整...
5   住的相當舒適，床舒服枕頭軟硬適中，飯店乾淨整潔，泡湯設備完備，住的質感想當好。\r\n早餐有...
6        訂房留言回答快速，房間乾淨，早餐豐富。\n位置較偏僻，但地下平面停車位多。有開車算方便。
7                                   CP值高 ,但地點要交通工具或接駁
8       優：飯店人員服務非常用心及貼心，是個難忘的住宿經驗。\n缺：如能再增加自助洗衣設備會更棒！
9   飯店周遭飲食不便,且因未在捷運旁造成展覽結束後回飯店困難重重,南港展覽館在尖峰時刻很難叫到計...
10  櫃台服務人員有禮貌\n房間乾淨冷氣很夠, 浴室的熱水強度好也穩定\n因是出差目的, 對飯店要...
11  以比較嚴格的標準來看的話，隔音比較差一點，早餐還ok不到驚艷，我們半夜才洗澡熱水沒有很熱，但...
12                       很不錯的旅店...早餐菜色可以再多一些變化...會更好!
13                                 很棒的飯店\n下次有來還會來住喔\n
14                                 很棒的飯店\n下次有來還會來住喔\n
15  地下停車場是我去過的飯店最寬敞最好停也最方便的飯店，我好幾次再回來都是因為這個停車場的緣故，...
16  優點 : 櫃台親切有禮,大廰環境整潔\n缺點: \n1.櫃台小姐說要幫我由高級客房升等豪華房...
17  當天是初四.自行開車,我家的噗噗君大概有1米9.飯店的停車場在地下室,很好停.不是機械式的....
18  1. 沒迎賓水果( 以前都有的)\n2. 床上枕頭只有一只( 以前都兩只), 落枕後發現一只...
19  這趟旅行是家族之旅，有3歲的小孩同行，房務安排了壁貼與玩具都齊全的孩童房，這點蠻驚喜的，小朋...

In [28]:
dataframe.to_csv('v1.csv')

In [208]:
f= pd.read_csv('v2.csv')
empt=[]
for i in range(len(f)):
    empt.append("")
f["level"]=empt

In [209]:
f3= pd.read_csv('v3_2.csv')
empt=[]
for i in range(len(f3)):
    empt.append("")
f3["level"]=empt

In [210]:
f

Unnamed: 0                                            comment  score  \
0             0  外籍員工的笑容與態度，明顯優於台籍員工。以晶華的收費與台灣飯店服務龍頭的水準，員工教育訓練明...    6.8   
1             1                                  對待有嬰兒的旅客非常nice!!!    9.6   
2             2                                      Pleasure stay   10.0   
3             3                      內有少數飯店設施有的三溫暖，裡頭潔淨度也很夠，值得再次住宿   10.0   
4             4  房間寬敞設備新穎典雅, 有免費Lounge, 服務極佳早餐好吃, 元宵節還提供免費畫燈籠與吃...    9.6   
..          ...                                                ...    ...   
941         941                                           非常好，服務周到    9.6   
942         942                                   香格里拉的服務質素 不用多說了吧   10.0   
943         943                                連續住了5天，早餐天天一樣，沒有更新。    6.8   
944         944  名符其實的高級酒店, 雖然不近捷運站, 但在台灣打計程車是常識吧?? 在12月31晚入住,房...    2.0   
945         945                               絕對有五星級酒店的風範！偶爾試一下也無防    9.2   

    level  
0          
1          
2          
3          
4          
..    ...  
941        
942        
943        
944        
945        

[946 rows x 4 columns]

In [211]:
for i in range(len(f)):
    if f.score.values[i]>=9:
        f.level.values[i]="0"
    elif f.score.values[i]>7:
        f.level.values[i]="1"
    else:
        f.level.values[i]="2"

In [212]:
for i in range(len(f3)):
    if f3.score.values[i]>=9:
        f3.level.values[i]="0"
    elif f3.score.values[i]>7:
        f3.level.values[i]="1"
    else:
        f3.level.values[i]="2"

In [213]:
f=f.append(f3)


In [214]:
fd1= pd.DataFrame(f["comment"],columns=["comment"])

In [215]:
fd1["level"]=f["level"]

In [216]:
fd1= pd.DataFrame(f["comment"],columns=["comment"])
fd1["level"]=f["level"]

In [217]:
fd1

comment level
0    外籍員工的笑容與態度，明顯優於台籍員工。以晶華的收費與台灣飯店服務龍頭的水準，員工教育訓練明...     2
1                                    對待有嬰兒的旅客非常nice!!!     0
2                                        Pleasure stay     0
3                        內有少數飯店設施有的三溫暖，裡頭潔淨度也很夠，值得再次住宿     0
4    房間寬敞設備新穎典雅, 有免費Lounge, 服務極佳早餐好吃, 元宵節還提供免費畫燈籠與吃...     0
..                                                 ...   ...
896  1.性價比頗高，價格很優惠。2.停車場為單一出入口，需要搭車梯，等候時容易跟旁邊新時代購物中...     1
897                                      在購物中心旁邊，交通極方便     1
898  位置非常好，離新時代購務中心門口只有幾步路，過個馬路也就到後車站地下道了，就算是下雨天也不太...     1
899  飯店位於台中火車站後站步行不到5分鐘的位置，且附有停車位,需要在車梯前，等候專人引導停車,停...     1
900  入住時間: 10/21(日)~10/22(一)(共1晚)\n房型: 標準房(兩床) (共1間...     1

[1847 rows x 2 columns]

In [262]:
train_data={"comment":fd1[:700]['comment'],'level':fd1[:700]['level']}
test_data={"comment":fd1[700:]['comment'],'level':fd1[700:]['level']}

In [263]:
count_vect=CountVectorizer(max_features=None)
X_train_counts = count_vect.fit_transform(train_data["comment"].values.astype('U'))

    
print("train data shape using CountVectorizer")
print(X_train_counts.shape)

X_test_counts=count_vect.transform(test_data["comment"].values.astype('U'))
print("test data shape using CountVectorizer")
print(X_test_counts.shape)


train data shape using CountVectorizer
(700, 4389)
test data shape using CountVectorizer
(1147, 4389)


In [264]:
MultinomialNB_clf=MultinomialNB()
print("*"*50)
print("MultinomialNB classifier with CountVectorizer")
print(MultinomialNB_clf)
MultinomialNB_clf.fit(X_train_counts, train_data["level"])

**************************************************
MultinomialNB classifier with CountVectorizer
MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [265]:
def show_result(predicted,predicted_proba,target):
    print("confusion matrix:")
    print(confusion_matrix(predicted, target))
    
    print('accuracy:')
    print(accuracy_score(predicted,target))

In [266]:
print('evaluation on train data')
predicted=MultinomialNB_clf.predict(X_train_counts)
#print(predicted)
predicted_proba=MultinomialNB_clf.predict_proba(X_train_counts)
show_result(predicted,predicted_proba,train_data['level'])

print("-"*100)
print('evaluation on test data')

predicted=MultinomialNB_clf.predict(X_test_counts)
#print(predicted)
#ans["class"]=predicted
predicted_proba=MultinomialNB_clf.predict_proba(X_test_counts)

show_result(predicted,predicted_proba,test_data["level"])

evaluation on train data
confusion matrix:
[[370  14  12]
 [  1 242   2]
 [  0   0  59]]
accuracy:
0.9585714285714285
----------------------------------------------------------------------------------------------------
evaluation on test data
confusion matrix:
[[496 391 134]
 [ 48  62  16]
 [  0   0   0]]
accuracy:
0.4864864864864865
